# This is a basic workflow to help you get started with Actions

name: First Workflow
on: workflow_dispatch
jobs:
  first_job:  
    runs-on: ubuntu-latest
    steps:
      - name : Print Greeting
        run : echo "Hello , Namaste"
      - name : Print closing message
        run : echo " Tata , good bye , subhrathri"
